opdFullName = {
    "setda":"Sekretariat Daerah",
    "bkpsdm":"Badan Kepegawaian dan Pengembangan Sumber Daya Manusia",
    "bakesbangpol":"Badan Kesatuan Bangsa dan Politik",
    "bpbd":"Badan Penanggulangan Bencana Daerah",
    "bapenda":"Badan Pendapatan Daerah",
    "pembangunan":"Bagian Administrasi Pembangunan Sekretariat Daerah",
    "hukum": "Bagian Hukum Sekretariat Daerah",
    "kesra":"Bagian Kesejahteraan Rakyat Sekretariat Daerah",
    "organisasi": "Bagian Organisasi Sekretariat Daerah",
    "pemerintahan":"Bagian Pemerintahan Sekretariat Daerah",
    "pbj":"Bagian Pengadaaan Barang/Jasa Sekretariat Daerah",
    "perekonomian":"Bagian Perekonomian dan Sumber Daya Alam Sekretariat Daerah",
    "renkeu":"Bagian Perencanaan dan Keuangan Sekretariat Daerah",
    "prokompim":"Bagian Protokol dan Komunikasi Pimpinan Sekretariat Daerah",
    "umum":"Bagian Umum Sekretariat Daerah",
    "disbudporapar":"Dinas Kebudayaan, Kepemudaan, Keolahragaan dan Pariwisata",
    "disdukcapil":"Dinas Kependudukan dan Pencatatan Sipil",
    "dinkes":"Dinas Kesehatan",
    "diskominfo":"Dinas Komunikasi dan Informatika",
    "dinkopum":"Dinas Koperasi dan Usaha Mikro",
    "dlh":"Dinas Lingkungan Hidup",
    "dispari":"Dinas Pangan dan Perikanan",
    "dpupr":"Dinas Pekerjaan Umum dan Penataan Ruang",
    "dpmd":"Dinas Pemberdayaan Masyarakat dan Desa",
    "dpmptsp":"Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
    "dispendik":"Dinas Pendidikan",
    "dp2kbp2":"Dinas Pengendalian Penduduk, Keluarga Berencana dan Pemberdayaan Perempuan",
    "disperindag":"Dinas Perindustrian dan Perdagangan",
    "disperka":"Dinas Perpustakaan dan Kearsipan",
    "disperta":"Dinas Pertanian",
    "dprkp2":"Dinas Perumahan Rakyat, Kawasan Permukiman dan Perhubungan",
    "dinsos":"Dinas Sosial",
    "disnaker":"Dinas Tenaga Kerja",
    "inspektorat":"Inspektorat",
    "bangsal":"Kecamatan Bangsal",
    "dawarblandong":"Kecamatan Dawarblandong",
    "dlanggu":"Kecamatan Dlanggu",
    "gedeg":"Kecamatan Gedeg",
    "gondang":"Kecamatan Gondang",
    "jatirejo":"Kecamatan Jatirejo",
    "jetis":"Kecamatan Jetis",
    "kemlagi":"Kecamatan Kemlagi",
    "kutorejo":"Kecamatan Kutorejo",
    "mojoanyar":"Kecamatan Mojoanyar",
    "mojosari":"Kecamatan Mojosari",
    "ngoro":"Kecamatan Ngoro",
    "pacet":"Kecamatan Pacet",
    "pungging":"Kecamatan Pungging",
    "puri":"Kecamatan Puri",
    "sooko":"Kecamatan Sooko",
    "trawas":"Kecamatan Trawas",
    "trowulan":"Kecamatan Trowulan",
    "satpolpp":"Satuan Polisi Pamong Praja",
    "setwan":"Sekretariat DPRD",
    "rssoekandar":"RSUD Prof. dr. Soekandar",
    "rsbasoeni":"RSUD R. A. Basoeni",
    "pkmdlanggu":"Puskesmas Dlanggu",
    "pkmbangsal":"Puskesmas Bangsal",
    "pkmdawarblandong":"Puskesmas Dawarblandong",
    "pkmgayaman":"Puskesmas Gayaman",
    "pkmgedeg":"Puskesmas Gedeg",
    "pkmgondang":"Puskesmas Gondang",
    "pkmjatirejo":"Puskesmas Jatirejo",
    "pkmjetis":"Puskesmas Jetis",
    "pkmkedungsari":"Puskesmas Kedungsari",
    "pkmkemlagi":"Puskesmas Kemlagi",
    "pkmkutorejo":"Puskesmas Kutorejo",
    "pkmlespadangan":"Puskesmas Lespadangan",
    "pkmmanduro":"Puskesmas Manduro",
    "pkmmodopuro":"Puskesmas Modopuro",
    "pkmmojosari":"Puskesmas Mojosari",
    "pkmngoro":"Puskesmas Ngoro",
    "pkmpacet":"Puskesmas Pacet",
    "pkmpandan":"Puskesmas Pandan",
    "pkmpesanggrahan":"Puskesmas Pesanggrahan",
    "pkmpuri":"Puskesmas Puri",
    "pkmsooko":"Puskesmas Sooko",
    "pkmtawangsari":"Puskesmas Tawangsari",
    "pkmtrawas":"Puskesmas Trawas",
    "pkmtrowulan":"Puskesmas Trowulan",
    "pkmwatukenongo":"Puskesmas Watukenongo"
}

opdAccronym = ['setda', 'setwan', 'bkpsdm', 'bakesbangpol', 'bpbd', 'bapenda', 'pembangunan', 'hukum', 'kesra', 'organisasi', 'pemerintahan', 'pbj', 'perekonomian', 'renkeu', 'prokompim', 'umum', 'disbudporapar', 'disdukcapil', 'dinkes', 'diskominfo', 'dinkopum', 'dlh', 'dispari', 'dpupr', 'dpmd', 'dpmptsp', 'dispendik', 'dp2kbp2', 'disperindag', 'disperka', 'disperta', 'dprkp2', 'dinsos', 'disnaker', 'inspektorat', 'satpolpp','rssoekandar', 'rsbasoeni', 'bangsal', 'dawarblandong', 'dlanggu', 'gedeg', 'gondang', 'jatirejo', 'jetis', 'kemlagi', 'kutorejo', 'mojoanyar', 'mojosari', 'ngoro', 'pacet', 'pungging', 'puri', 'sooko', 'trawas', 'trowulan', 'pkmdlanggu', 'pkmbangsal', 'pkmdawarblandong', 'pkmgayaman', 'pkmgedeg', 'pkmgondang', 'pkmjatirejo', 'pkmjetis', 'pkmkedungsari', 'pkmkemlagi', 'pkmkutorejo', 'pkmlespadangan', 'pkmmanduro', 'pkmmodopuro', 'pkmmojosari', 'pkmngoro', 'pkmpacet', 'pkmpandan', 'pkmpesanggrahan', 'pkmpuri', 'pkmsooko', 'pkmtawangsari', 'pkmtrawas', 'pkmtrowulan', 'pkmwatukenongo']

if __name__ == "__main__":
    print(opdFullName.keys())